name: Merge Playwright report

inputs:
  blob-pattern:
    description: 'Artifact name pattern for blob reports'
    required: false
    default: 'blob-report-*'
  blob-path:
    description: 'Path to download blob reports'
    required: false
    default: 'all-blob-reports'
  report-name:
    description: 'Name for merged report artifact'
    required: false
    default: 'playwright-report'
  report-path:
    description: 'Path for merged report output'
    required: false
    default: 'playwright-report'
  retention-days:
    description: 'Artifact retention days'
    required: false
    default: '5'

outputs:
  report-url:
    description: 'Download URL for merged report artifact'
    value: ${{ steps.resolve-url.outputs.report_url }}

runs:
  using: composite
  steps:
    - name: Download shard reports
        
      uses: actions/download-artifact@v4
      with:
        path: ${{ inputs.blob-path }}
        pattern: ${{ inputs.blob-pattern }}
        merge-multiple: true

    - name: Merge Playwright reports
      shell: bash
      run: |
        mkdir -p "${{ inputs.report-path }}/trace"
        cp -r "${{ inputs.blob-path }}"/*/trace/* "${{ inputs.report-path }}/trace" || true
        npx playwright merge-reports --reporter=html "${{ inputs.blob-path }}"

    - name: Upload merged report
      id: upload-report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.report-name }}
        path: ${{ inputs.report-path }}
        retention-days: ${{ inputs.retention-days }}

    - name: Resolve report download URL
      id: resolve-url
      uses: actions/github-script@v7
      with:
        github-token: ${{ env.GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        script: |
          const artifactName = '${{ inputs.report-name }}';
          let reportUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
          try {
            const { data } = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
            const artifact = data.artifacts.find((a) => a.name === artifactName);
            if (artifact?.archive_download_url) {
              const res = await fetch(artifact.archive_download_url, {
                method: 'GET',
                headers: { Authorization: `token ${process.env.GITHUB_TOKEN}` },
                redirect: 'manual',
              });
              const loc = res.headers.get('location');
              if (loc) reportUrl = loc;
            }
          } catch (e) {
            core.warning(`Could not resolve report URL: ${e.message}`);
          }
          core.setOutput('report_url', reportUrl);
