// Story 0.9 Task 2 step 7 owner:
// consume the shared HTTP contracts from the API here, so Nest controllers stay thin adapters.
//
// Why this step matters:
// the contract source of truth lives in @couture/api-client. This bridge lets the API use that
// package surface directly instead of redefining request/response shapes inside controller code.
export {
  alertPreferencesSchema,
  alertRuleSchema,
  getAlertPreferencesResponseSchema,
  updateAlertRulesInputSchema,
  updateAlertRulesResponseSchema,
  updateNotificationPreferencesInputSchema,
  updateNotificationPreferencesResponseSchema,
  type AlertPreferences,
  type AlertRule,
  type GetAlertPreferencesResponse,
  type UpdateAlertRulesInput,
  type UpdateAlertRulesResponse,
  type UpdateNotificationPreferencesInput,
  type UpdateNotificationPreferencesResponse,
  type ConsentLevel,
  type GuardianConsentInput,
  type GuardianConsentRevokeInput,
  type GuardianConsentRevokeResponse,
  type GuardianInvitationAcceptInput,
  type GuardianInvitationAcceptResponse,
  type GuardianInvitationInput,
  type GuardianInvitationResponse,
  type SignupInput,
  type SignupResponse,
  consentLevelSchema,
  guardianConsentInputSchema,
  guardianConsentRevokeInputSchema,
  guardianConsentRevokeResponseSchema,
  guardianConsentResponseSchema,
  guardianInvitationAcceptInputSchema,
  guardianInvitationAcceptResponseSchema,
  guardianInvitationInputSchema,
  guardianInvitationResponseSchema,
  signupInputSchema,
  signupResponseSchema,
  apiHealthResponseSchema,
  eventsPollInvalidSinceResponseSchema,
  eventsPollQuerySchema,
  eventsPollResponseSchema,
  type ModerationActionInput,
  moderationActionInputSchema,
  moderationActionResponseSchema,
  queueHealthResponseSchema,
  defaultSupportedLocale,
  resolveAcceptLanguage,
  resolveSupportedLocale,
  supportedLocales,
  supportedLocaleSchema,
  type SupportedLocale,
  userProfileResponseSchema,
  userPreferencesInputSchema,
  userPreferencesResponseSchema,
  type UserPreferencesInput,
  type UserPreferencesResponse,
  latestWeatherResponseSchema,
  type LatestWeatherResponse,
  type WeatherAlert,
  type WeatherCondition,
  type WeatherProvider,
  createSavedLocationInputSchema,
  createSavedLocationResponseSchema,
  deleteSavedLocationResponseSchema,
  listSavedLocationsResponseSchema,
  savedLocationSchema,
  setPrimarySavedLocationResponseSchema,
  updateSavedLocationInputSchema,
  updateSavedLocationResponseSchema,
  type CreateSavedLocationInput,
  type CreateSavedLocationResponse,
  type DeleteSavedLocationResponse,
  type ListSavedLocationsResponse,
  type SavedLocation,
  type SetPrimarySavedLocationResponse,
  type UpdateSavedLocationInput,
  type UpdateSavedLocationResponse,
  ritualQueryParamsSchema,
  ritualResponseSchema,
  type RitualResponse,
  type RitualQueryParams,
  type ScenarioOutfit,
  type ScenarioName,
  scenarioOutfitSchema,
  scenarioNameSchema,
  comfortRunSchema,
  windToleranceSchema,
  precipPreparednessSchema,
  comfortPreferencesSchema,
  comfortPreferencesResponseSchema,
  updateComfortPreferencesInputSchema,
  updateComfortPreferencesResponseSchema,
  type ComfortRun,
  type WindTolerance,
  type PrecipPreparedness,
  type ComfortPreferences,
  type ComfortPreferencesResponse,
  type UpdateComfortPreferencesInput,
  type UpdateComfortPreferencesResponse,
} from '@couture/api-client/contracts/http'
