// Story 0.9 Task 2 step 7 owner:
// consume the shared HTTP contracts from the API here, so Nest controllers stay thin adapters.
//
// Why this step matters:
// the contract source of truth lives in @couture/api-client. This bridge lets the API use that
// package surface directly instead of redefining request/response shapes inside controller code.
export {
  alertPreferencesSchema,
  alertRuleSchema,
  getAlertPreferencesResponseSchema,
  updateAlertRulesInputSchema,
  updateAlertRulesResponseSchema,
  updateNotificationPreferencesInputSchema,
  updateNotificationPreferencesResponseSchema,
  type AlertPreferences,
  type AlertRule,
  type GetAlertPreferencesResponse,
  type UpdateAlertRulesInput,
  type UpdateAlertRulesResponse,
  type UpdateNotificationPreferencesInput,
  type UpdateNotificationPreferencesResponse,
  type ConsentLevel,
  type GuardianConsentInput,
  type GuardianConsentRevokeInput,
  type GuardianConsentRevokeResponse,
  type GuardianInvitationAcceptInput,
  type GuardianInvitationAcceptResponse,
  type GuardianInvitationInput,
  type GuardianInvitationResponse,
  type SignupInput,
  type SignupResponse,
  consentLevelSchema,
  guardianConsentInputSchema,
  guardianConsentRevokeInputSchema,
  guardianConsentRevokeResponseSchema,
  guardianConsentResponseSchema,
  guardianInvitationAcceptInputSchema,
  guardianInvitationAcceptResponseSchema,
  guardianInvitationInputSchema,
  guardianInvitationResponseSchema,
  signupInputSchema,
  signupResponseSchema,
  apiHealthResponseSchema,
  eventsPollInvalidSinceResponseSchema,
  eventsPollQuerySchema,
  eventsPollResponseSchema,
  type ModerationActionInput,
  moderationActionInputSchema,
  moderationActionResponseSchema,
  queueHealthResponseSchema,
  defaultSupportedLocale,
  resolveAcceptLanguage,
  resolveSupportedLocale,
  supportedLocales,
  supportedLocaleSchema,
  type SupportedLocale,
  userProfileResponseSchema,
  userPreferencesInputSchema,
  userPreferencesResponseSchema,
  type UserPreferencesInput,
  type UserPreferencesResponse,
  latestWeatherResponseSchema,
  type LatestWeatherResponse,
  type WeatherAlert,
  type WeatherCondition,
  type WeatherProvider,
  createSavedLocationInputSchema,
  createSavedLocationResponseSchema,
  deleteSavedLocationResponseSchema,
  listSavedLocationsResponseSchema,
  savedLocationSchema,
  setPrimarySavedLocationResponseSchema,
  updateSavedLocationInputSchema,
  updateSavedLocationResponseSchema,
  type CreateSavedLocationInput,
  type CreateSavedLocationResponse,
  type DeleteSavedLocationResponse,
  type ListSavedLocationsResponse,
  type SavedLocation,
  type SetPrimarySavedLocationResponse,
  type UpdateSavedLocationInput,
  type UpdateSavedLocationResponse,
  ritualQueryParamsSchema,
  ritualResponseSchema,
  type RitualResponse,
  type RitualQueryParams,
  type ScenarioOutfit,
  type ScenarioName,
  scenarioOutfitSchema,
  scenarioNameSchema,
  comfortRunSchema,
  windToleranceSchema,
  precipPreparednessSchema,
  comfortPreferencesSchema,
  comfortPreferencesResponseSchema,
  updateComfortPreferencesInputSchema,
  updateComfortPreferencesResponseSchema,
  type ComfortRun,
  type WindTolerance,
  type PrecipPreparedness,
  type ComfortPreferences,
  type ComfortPreferencesResponse,
  type UpdateComfortPreferencesInput,
  type UpdateComfortPreferencesResponse,
  // Story 5.1 commerce. This block is hand-maintained and does NOT re-export *,
  // so a schema that exists in @couture/api-client but is missing here is
  // simply invisible to every API controller.
  affiliateSurfaceSchema,
  affiliateConversionStatusSchema,
  shopThisLookSchema,
  commercePreferenceSchema,
  commercePreferenceResponseSchema,
  updateCommercePreferenceInputSchema,
  updateCommercePreferenceResponseSchema,
  affiliateClickRequestSchema,
  affiliateClickResponseSchema,
  affiliateWebhookHeadersSchema,
  affiliateWebhookPayloadSchema,
  affiliateWebhookResponseSchema,
  WEBHOOK_SIGNATURE_INVALID_MESSAGE,
  COMMERCE_OPTED_OUT_MESSAGE,
  COMMERCE_AUDIENCE_INELIGIBLE_MESSAGE,
  COMMERCE_OFFER_NOT_FOUND_MESSAGE,
  COMMERCE_OFFER_INVALID_MESSAGE,
  COMMERCE_DISABLED_MESSAGE,
  type ShopThisLook,
  type CommercePreference,
  type CommercePreferenceResponse,
  type UpdateCommercePreferenceInput,
  type UpdateCommercePreferenceResponse,
  type AffiliateClickRequest,
  type AffiliateClickResponse,
  type AffiliateWebhookHeaders,
  type AffiliateWebhookPayload,
  type AffiliateWebhookResponse,
  // Story 5.2 premium subscription. Same hand-maintained rule as above.
  subscriptionPlanSchema,
  entitlementStoreSchema,
  subscriptionStatusSchema,
  subscriptionSchema,
  subscriptionResponseSchema,
  checkoutSessionRequestSchema,
  checkoutSessionResponseSchema,
  portalSessionResponseSchema,
  billingWebhookResponseSchema,
  COMMERCE_SUBSCRIPTION_DISABLED_MESSAGE,
  SUBSCRIPTION_ALREADY_ACTIVE_MESSAGE,
  SUBSCRIPTION_NOT_FOUND_MESSAGE,
  SUBSCRIPTION_NOT_WEB_MANAGED_MESSAGE,
  SUBSCRIPTION_LEDGER_UNAVAILABLE_MESSAGE,
  BILLING_WEBHOOK_UNAUTHORIZED_MESSAGE,
  PREMIUM_REQUIRED_MESSAGE,
  type SubscriptionPlan,
  type EntitlementStore,
  type SubscriptionStatus,
  type Subscription,
  type SubscriptionResponse,
  type CheckoutSessionRequest,
  type CheckoutSessionResponse,
  type PortalSessionResponse,
  type BillingWebhookResponse,
  // Story 5.3 premium theme. Same hand-maintained rule as above.
  // PREMIUM_REQUIRED_MESSAGE is re-exported once, by the 5.2 block: it is the
  // guard's own 403 message and this story's PUT reuses it rather than
  // redefining a second copy.
  premiumThemeKeySchema,
  premiumThemeSchema,
  premiumThemeResponseSchema,
  updatePremiumThemeInputSchema,
  updatePremiumThemeResponseSchema,
  PREMIUM_THEME_OWNER_NOT_FOUND_MESSAGE,
  PREMIUM_THEMES_DISABLED_MESSAGE,
  type PremiumThemeKey,
  type PremiumTheme,
  type PremiumThemeResponse,
  type UpdatePremiumThemeInput,
  type UpdatePremiumThemeResponse,
} from '@couture/api-client/contracts/http'
