apiVersion: 1

datasources:
  - name: grafanacloud-couturecastobservability-prom
    uid: couturecast-prom
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
  - name: grafanacloud-couturecastobservability-traces
    uid: couturecast-traces
    type: tempo
    access: proxy
    url: http://127.0.0.1:3200
